name: Custom Windows x86 Client Generator
run-name: Custom Windows x86 Client Generator
on:
  workflow_dispatch:
env:
  # Toolchain versions (сохранены совместимые для Sciter x86)
  SCITER_RUST_VERSION: "1.75"
  RUST_VERSION: "1.75"
  MAC_RUST_VERSION: "1.81"
  CARGO_NDK_VERSION: "3.1.2"
  SCITER_ARMV7_CMAKE_VERSION: "3.29.7"
  SCITER_NASM_DEBVERSION: "2.15.05-1"
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.24.5"
  ANDROID_FLUTTER_VERSION: "3.24.5"
  FLUTTER_ELINUX_VERSION: "3.16.9"
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  ARMV7_VCPKG_COMMIT_ID: "6f29f12e82a8293156836ad81cc9bf5af41fe836"
  
  # Ваша кастомная конфигурация (перенесена из g-w-64.yml)
  VERSION: "1.4.5"
  NDK_VERSION: "r27c"
  appname: "SSQS"
  filename: "SSQS"
  compname: "Sigma-Soft"
  server: "rd.sigma-soft.ru"
  key: "kn5QUYXLEPBepybeHbyw9mzSibyGM8xsq6Eh8Zu5k40="
  apiServer: "https://rd.sigma-soft.ru"
  direction: "incoming"
  installation: "installationN"
  settings: "settingsN"
  passApproveMode: "password"
  permanentPassword: ""
  rdgen: "local"
  token: ""
  uuid: ""
  # Base64 настройки для клиентов
  custom: "eyJjb25uLXR5cGUiOiJpbmNvbWluZyIsImRpc2FibGUtaW5zdGFsbGF0aW9uIjoiWSIsImRpc2FibGUtc2V0dGluZ3MiOiJZIiwiYXBwLW5hbWUiOiJTaWdtYURlc2siLCJvdmVycmlkZS1zZXR0aW5ncyI6eyJ0aGVtZSI6ImxpZ2h0IiwiYWxsb3ctcmVtb3ZlLXdhbGxwYXBlciI6IlkifX0="
  
  iconlink_url: "false"
  iconlink_file: ""
  iconlink_uuid: ""
  logolink_url: "false"
  logolink_file: ""
  logolink_uuid: ""
  delayFix: "false"
  cycleMonitor: "false"
  xOffline: "false"
  removeNewVersionNotif: "true"
  runasadmin: "false"
  urlLink: "https://sigma-soft.ru"
  downloadLink: "https://sigma-soft.ru"
  
  UPLOAD_ARTIFACT: "true"
  SIGN_BASE_URL: "${{ secrets.SIGN_BASE_URL }}"
  STATUS_URL: ""

jobs:
  build-for-windows-sciter:
    name: Build Windows x86
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: i686-pc-windows-msvc, os: windows-2022, arch: x86, vcpkg-triplet: x86-windows-static }
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Save branding files
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "C:\branding"
          Copy-Item ".github/ssqs.ico" "C:\branding\ssqs.ico" -Force
          Copy-Item ".github/Logo.png" "C:\branding\Logo.png" -Force
          Write-Host "Branding files saved"        

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: ThisIsCradle/rustdesk
          ref: sigma-1.4.5
          submodules: recursive

      - name: Install ImageMagick on Windows
        run: |
          choco install -y imagemagick.app --no-progress
          Get-ChildItem -Path "${env:ProgramFiles}" | % { $_.FullName } | Select-String -Pattern "[\/\\]ImageMagick[^\/\\]*$" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

      # - name: Save branding files
      #   shell: pwsh
      #   run: |
      #     New-Item -ItemType Directory -Force -Path "C:\branding"
      #     Copy-Item ".github/ssqs.ico" "C:\branding\ssqs.ico" -Force
      #     Copy-Item ".github/Logo.png" "C:\branding\Logo.png" -Force
      #     Write-Host "Branding files saved"

      - name: change appname to custom
        if: env.appname != 'rustdesk'
        continue-on-error: true
        shell: bash
        run: |
          # ./Cargo.toml
          sed -i -e 's|description = "RustDesk Remote Desktop "|description = "${{ env.appname }} "|' ./Cargo.toml
          sed -i -e 's|ProductName = "RustDesk "|ProductName = "${{ env.appname }} "|' ./Cargo.toml
          sed -i -e 's|FileDescription = "RustDesk Remote Desktop "|FileDescription = "${{ env.appname }} "|' ./Cargo.toml
          sed -i -e 's|OriginalFilename = "rustdesk.exe "|OriginalFilename = "${{ env.appname }}.exe "|' ./Cargo.toml
          # ./libs/portable/Cargo.toml
          sed -i -e 's|description = "RustDesk Remote Desktop "|description = "${{ env.appname }} "|' ./libs/portable/Cargo.toml
          sed -i -e 's|ProductName = "RustDesk "|ProductName = "${{ env.appname }} "|' ./libs/portable/Cargo.toml
          sed -i -e 's|FileDescription = "RustDesk Remote Desktop "|FileDescription = "${{ env.appname }} "|' ./libs/portable/Cargo.toml
          sed -i -e 's|OriginalFilename = "rustdesk.exe "|OriginalFilename = "${{ env.appname }}.exe "|' ./libs/portable/Cargo.toml
          # ./libs/portable/src/main.rs
          sed -i -e 's|const APP_PREFIX: \&str = "rustdesk ";|const APP_PREFIX: \&str = "${{ env.appname }} ";|' ./libs/portable/src/main.rs
          # ./src/lang/en.rs
          if [ ! -z "${{ env.compname }}" ]; then
            find ./src/lang -name "*.rs" -exec sed -i '/powered_by_me/s|RustDesk|${{ env.compname }}|g' {} \;
          fi
          find ./src/lang -name "*.rs" -exec sed -i -e 's|RustDesk|${{ env.appname }}|' {} \;
          sed -i -e 's|RustDesk|${{ env.appname }}|' ./res/msi/Package/License.rtf

      - name: fix registry if appname has a space
        if: contains(env.appname, ' ')
        continue-on-error: true
        shell: bash
        run: |
          sed -i -e 's|reg add {}|reg add \\"{}\\"|' ./src/platform/windows.rs
          sed -i -e 's|reg add HKEY_CLASSES_ROOT\\\\.{ext} /f|reg add \\"HKEY_CLASSES_ROOT\\\\.{ext}\\" /f|' ./src/platform/windows.rs
          sed -i -e 's|reg add HKEY_CLASSES_ROOT\\\\.{ext}\\\\DefaultIcon /f|reg add \\"HKEY_CLASSES_ROOT\\\\.{ext}\\\\DefaultIcon\\" /f|' ./src/platform/windows.rs
          sed -i -e 's|reg add HKEY_CLASSES_ROOT\\\\.{ext}\\\\shell /f|reg add \\"HKEY_CLASSES_ROOT\\\\.{ext}\\\\shell\\" /f|' ./src/platform/windows.rs
          sed -i -e 's|reg add HKEY_CLASSES_ROOT\\\\.{ext}\\\\shell\\\\open /f|reg add \\"HKEY_CLASSES_ROOT\\\\.{ext}\\\\shell\\\\open\\" /f|' ./src/platform/windows.rs
          sed -i -e 's|reg add HKEY_CLASSES_ROOT\\\\.{ext}\\\\shell\\\\open\\\\command|reg add \\"HKEY_CLASSES_ROOT\\\\.{ext}\\\\shell\\\\open\\\\command\\"|' ./src/platform/windows.rs
          sed -i -e 's|reg add HKEY_CLASSES_ROOT\\\\{ext} /f|reg add \\"HKEY_CLASSES_ROOT\\\\{ext}\\" /f|' ./src/platform/windows.rs
          sed -i -e 's|reg add HKEY_CLASSES_ROOT\\\\{ext}\\\\shell /f|reg add \\"HKEY_CLASSES_ROOT\\\\{ext}\\\\shell\\" /f|' ./src/platform/windows.rs
          sed -i -e 's|reg add HKEY_CLASSES_ROOT\\\\{ext}\\\\shell\\\\open /f|reg add \\"HKEY_CLASSES_ROOT\\\\{ext}\\\\shell\\\\open\\" /f|' ./src/platform/windows.rs
          sed -i -e 's|reg add HKEY_CLASSES_ROOT\\\\{ext}\\\\shell\\\\open\\\\command /f|reg add \\"HKEY_CLASSES_ROOT\\\\{ext}\\\\shell\\\\open\\\\command\\" /f|' ./src/platform/windows.rs
          sed -i -e 's|{subkey}|\\"{subkey}\\"|' ./src/platform/windows.rs
          sed -i -e 's|reg delete HKEY_CLASSES_ROOT\\\\.{ext} /f|reg delete \\"HKEY_CLASSES_ROOT\\\\.{ext}\\" /f|' ./src/platform/windows.rs
          sed -i -e 's|reg delete HKEY_CLASSES_ROOT\\\\{ext} /f|reg delete \\"HKEY_CLASSES_ROOT\\\\{ext}\\" /f|' ./src/platform/windows.rs

      - name: change company name
        if: env.compname != 'Purslane Ltd'
        continue-on-error: true
        shell: bash
        run: |
          sed -i -e 's|PURSLANE|${{ env.compname }}|' ./res/msi/preprocess.py
          sed -i -e 's|Purslane Ltd|${{ env.compname }}|' ./res/msi/preprocess.py
          sed -i -e 's|Copyright  &copy; 2025 Purslane Ltd.|Copyright \&copy; 2025 ${{ env.compname }}|' ./src/ui/index.tis
          sed -i -e 's|Purslane Ltd|${{ env.compname }}|' ./Cargo.toml
          sed -i -e 's|Purslane Ltd|${{ env.compname }}|' ./libs/portable/Cargo.toml
          sed -i -e 's|Purslane Ltd.|${{ env.compname }}|' ./res/setup.nsi

      - name: change url to custom
        if: env.urlLink != 'https://rustdesk.com'
        continue-on-error: true
        shell: bash
        run: |
          sed -i -e 's|Homepage: https://rustdesk.com|Homepage: ${{ env.urlLink }}|' ./build.py
          sed -i -e "s| <div .link .custom-event url='https://rustdesk.com' >| <div .link .custom-event url='${{ env.urlLink }}' >|" ./src/ui/index.tis
          sed -i -e "s| <div .link .custom-event url='https://rustdesk.com/privacy.html' >| <div .link .custom-event url='${{ env.urlLink }}/privacy.html' >|" ./src/ui/index.tis
          sed -i -e "s|https://rustdesk.com/|${{env.urlLink }}|" ./res/setup.nsi
          sed -i -e 's|rustdesk.com|${{ env.urlLink }}|' ./res/msi/Package/License.rtf

      - name: change download link to custom
        if: env.downloadLink != 'https://rustdesk.com/download'
        continue-on-error: true
        shell: bash
        run: |
          sed -i -e 's|https://rustdesk.com/download|${{ env.downloadLink }}|' ./src/ui/index.tis

      - name: set server, key, and apiserver
        continue-on-error: true
        shell: bash
        run: |
          sed -i -e 's|rs-ny.rustdesk.com|${{ env.server }}|' ./libs/hbb_common/src/config.rs
          sed -i -e 's|OeVuKk5nlHiXp+APNn0Y3pC1Iwpwn44JGqrQCsWqmBw=|${{ env.key }}|' ./libs/hbb_common/src/config.rs
          sed -i -e 's|https://admin.rustdesk.com|${{ env.apiServer }}|' ./src/common.rs
          sed -i -e 's| <span >{translate( "Ready ")},  <span .link #setup-server >{translate( "setup_server_tip ")} </span > </span >|translate( "Ready ")|' ./src/ui/index.tis

      - name: allow custom.txt
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 1
          max_attempts: 3
          shell: pwsh
          continue_on_error: true
          command: |
            Invoke-WebRequest -Uri https://raw.githubusercontent.com/bryangerlach/rdgen/refs/heads/master/.github/patches/allowCustom.py -OutFile allowCustom.py
            python allowCustom.py
            Invoke-WebRequest -Uri https://raw.githubusercontent.com/bryangerlach/rdgen/refs/heads/master/.github/patches/removeSetupServerTip.diff -OutFile removeSetupServerTip.diff
            git apply removeSetupServerTip.diff

      - name: Install LLVM and Clang
        uses: rustdesk-org/install-llvm-action-32bit@master
        with:
          version: ${{ env.LLVM_VERSION }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly-2023-10-13-${{ matrix.job.target }}
          targets: ${{ matrix.job.target }}
          components: "rustfmt"

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.job.os }}-sciter

      - name: Setup vcpkg with Github Actions binary cache
        uses: lukka/run-vcpkg@v11
        with: 
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false

      - name: Install vcpkg dependencies
        env:
          VCPKG_DEFAULT_HOST_TRIPLET: ${{ matrix.job.vcpkg-triplet }}
        run: |
          if ! $VCPKG_ROOT/vcpkg \
            install \
            --triplet ${{ matrix.job.vcpkg-triplet }} \
            --x-install-root= "$VCPKG_ROOT/installed "; then
            find  "${VCPKG_ROOT}/ " -name  "*.log " | while read -r _1; do
              echo  "$_1: "
              echo  "====== "
              cat  "$_1 "
              echo  "====== "
              echo  " "
            done
            exit 1
          fi
          head -n 100  "${VCPKG_ROOT}/buildtrees/ffmpeg/build-${{ matrix.job.vcpkg-triplet }}-rel-out.log " || true
        shell: bash

      - name: icon stuff
        continue-on-error: true
        shell: bash
        run: |
          mv ./res/icon.ico ./res/icon.ico.bak
          mv ./res/icon.png ./res/icon.png.bak
          mv ./res/tray-icon.ico ./res/tray-icon.ico.bak

      - name: magick stuff
        continue-on-error: true
        shell: pwsh
        run: |
          Copy-Item "C:\branding\ssqs.ico" "./res/icon.ico" -Force
          Copy-Item "./res/icon.ico" "./res/tray-icon.ico" -Force
          magick "./res/icon.ico[0]" -resize 32x32 "./res/32x32.png"
          magick "./res/icon.ico[0]" -resize 64x64 "./res/64x64.png"
          magick "./res/icon.ico[0]" -resize 128x128 "./res/128x128.png"
          magick "./res/128x128.png" -resize 200% "./res/128x128@2x.png"
          magick "./res/icon.ico[0]" "./res/icon.png"
          Write-Host "Custom app icon applied"

      - name: ui.rs icon
        continue-on-error: true
        shell: bash
        run: |
          cp ./src/ui.rs ./src/ui.rs.bak
          b64=$(base64 -w0 < ./res/icon.png)
          perl -0777 -pe "s|iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHL[A-Za-z0-9+/=]+|$b64|g" -i.bak ./src/ui.rs
          b64=" "

      - name: fix connection delay
        continue-on-error: true
        if: ${{ env.delayFix == 'true' }}
        shell: bash
        run: |
          sed -i -e 's|!key.is_empty()|false|' ./src/client.rs

      - name: removeNewVersionNotif
        continue-on-error: true
        if: env.removeNewVersionNotif == 'true'
        shell: bash
        run: | 
          sed -i -e 's|{software_update_url ? <UpdateMe /> :  " " }||' ./src/ui/index.tis
          sed -i '/let (request, url) =/,/Ok(())/{/Ok(())/!d}' ./src/common.rs

      - name: Build rustdesk
        id: build
        shell: bash
        run: |
          python3 res/inline-sciter.py
          # Patch sciter x86
          sed -i 's/branch = "dyn "/branch = "dyn_x86 "/g' ./Cargo.toml
          cargo build --features inline,vram,hwcodec --release --bins
          mkdir -p ./Release
          mv ./target/release/rustdesk.exe ./Release/rustdesk.exe
          curl -LJ -o ./Release/sciter.dll https://github.com/c-smile/sciter-sdk/raw/master/bin.win/x32/sciter.dll
          echo "output_folder=./Release" >> $GITHUB_OUTPUT
          curl -LJ -o ./usbmmidd_v2.zip https://github.com/rustdesk-org/rdev/releases/download/usbmmidd_v2/usbmmidd_v2.zip
          unzip usbmmidd_v2.zip
          rm -rf ./usbmmidd_v2/deviceinstaller.exe ./usbmmidd_v2/usbmmidd.bat
          mv ./usbmmidd_v2 ./Release || true

      - name: zip dlls
        continue-on-error: true
        shell: pwsh
        run: |
          Compress-Archive -Path ./Release/*.dll, ./Release/*.exe -DestinationPath ./Release/unsigned_files.zip -CompressionLevel Fastest

      - name: sign dlls
        continue-on-error: true
        shell: bash
        run: |
          if [ ! -z "${{ secrets.SIGN_BASE_URL }}" ] && [ ! -z "${{ secrets.SIGN_API_KEY }}" ]; then
            curl -X POST -F "file=@./Release/unsigned_files.zip" \
              -H "X-API-KEY: ${{ secrets.SIGN_API_KEY }}" \
              -m 900 \
              "${{ secrets.SIGN_BASE_URL }}/sign/" -o ./Release/signed_files.zip
          else
            echo "Signing skipped - signing URL or API key not configured"
            cp ./Release/unsigned_files.zip ./Release/signed_files.zip
          fi

      - name: unzip dlls
        continue-on-error: true
        shell: pwsh
        run: |
          Expand-Archive -Path ./Release/signed_files.zip -DestinationPath ./Release/ -Force
          Remove-Item ./Release/unsigned_files.zip
          Remove-Item ./Release/signed_files.zip

      - name: Create custom.txt file
        shell: bash
        run: |
          echo -n "${{ env.custom }}" | cat > ./Release/custom.txt

      - name: Build self-extracted executable
        shell: bash
        run: |
          mv "./Release/rustdesk.exe" "./Release/${{ env.appname }}.exe" || echo "rustdesk.exe"
          sed -i '/dpiAware/d' res/manifest.xml
          pushd ./libs/portable
          pip3 install -r requirements.txt
          python3 ./generate.py -f ../../Release/ -o . -e "../../Release/${{ env.appname }}.exe"
          popd
          mkdir -p ./SignOutput
          mv ./target/release/rustdesk-portable-packer.exe "./SignOutput/rustdesk.exe"

      - name: zip exe
        continue-on-error: true
        shell: pwsh
        run: |
          Compress-Archive -Path ./SignOutput/*.exe -DestinationPath ./SignOutput/unsigned_files.zip -CompressionLevel Fastest

      - name: sign exe
        continue-on-error: true
        shell: bash
        run: |
          if [ ! -z "${{ secrets.SIGN_BASE_URL }}" ] && [ ! -z "${{ secrets.SIGN_API_KEY }}" ]; then
            curl -X POST -F "file=@./SignOutput/unsigned_files.zip" \
              -H "X-API-KEY: ${{ secrets.SIGN_API_KEY }}" \
              -m 900 \
              "${{ secrets.SIGN_BASE_URL }}/sign/" -o ./SignOutput/signed_files.zip
          else
            echo "Signing skipped - signing URL or API key not configured"
            cp ./SignOutput/unsigned_files.zip ./SignOutput/signed_files.zip
          fi

      - name: unzip exe
        continue-on-error: true
        shell: pwsh
        run: |
          Expand-Archive -Path ./SignOutput/signed_files.zip -DestinationPath ./SignOutput/ -Force
          Remove-Item ./SignOutput/unsigned_files.zip
          Remove-Item ./SignOutput/signed_files.zip

      - name: rename rustdesk.exe to filename.exe
        run: |
          mv ./SignOutput/rustdesk.exe "./SignOutput/${{ env.filename }}.exe" || echo "rustdesk"

      - name: Upload SigmaDesk x86 artifacts
        if: env.UPLOAD_ARTIFACT == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: SigmaDesk-Windows-x86
          path: |
            ./SignOutput/${{ env.filename }}.exe

      - name: send file to rdgen server
        if: ${{ env.rdgen == 'true' }}
        shell: bash
        run: |
          curl -i -X POST -H "Content-Type: multipart/form-data" -H "Authorization: Bearer ${{ env.token }}" -F "file=@./SignOutput/${{ env.filename }}.exe" -F "uuid=${{ env.uuid }}" ${{ secrets.GENURL }}/save_custom_client

      - name: send file to api server
        if: ${{ env.rdgen == 'false' }}
        shell: bash
        run: |
          curl -i -X POST -H "Content-Type: multipart/form-data" -H "Authorization: Bearer ${{ env.token }}" -F "file=@./SignOutput/${{ env.filename }}.exe" ${{ env.apiServer }}/api/save_custom_client

  cleanup:
    needs: [build-for-windows-sciter]
    runs-on: ubuntu-latest
    continue-on-error: true
    if: always()
    steps:
      - name: Delete secrets artifact
        if: always()
        uses: geekyeggo/delete-artifact@v5
        with:
          name: encrypted-secrets-zip
